//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelfoodsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vel_restro_empdepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vel_restro_empdepartment()
        {
            this.vel_restro_empregistration = new HashSet<vel_restro_empregistration>();
        }
    
        public int empdepartement_id { get; set; }
        public string empdepartement_name { get; set; }
        public string empdepartement_status { get; set; }
        public int restaurent_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vel_restro_empregistration> vel_restro_empregistration { get; set; }
        public virtual vel_restro_restaurent vel_restro_restaurent { get; set; }
    }
}
