//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelfoodsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vel_restro_itemname
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vel_restro_itemname()
        {
            this.vel_restro_order = new HashSet<vel_restro_order>();
            this.vel_restro_table_transfer = new HashSet<vel_restro_table_transfer>();
        }
    
        public int itemname_id { get; set; }
        public string itemname_item_name { get; set; }
        public string itemname_description { get; set; }
        public string itemname_reportingname { get; set; }
        public System.DateTime itemname_active_from { get; set; }
        public string itemname_status { get; set; }
        public decimal item_dinein_amount { get; set; }
        public int item_dinein_tax { get; set; }
        public decimal item_takeaway_amount { get; set; }
        public int item_takeaway_tax { get; set; }
        public decimal item_homedelivary_amount { get; set; }
        public int item_homedelivary_tax { get; set; }
        public decimal item_homedelivery_deliverycharges { get; set; }
        public int restaurent_id { get; set; }
        public int itemcategory_id { get; set; }
        public Nullable<decimal> itemname_dinein_total { get; set; }
        public Nullable<decimal> itemname_takeaway_total { get; set; }
        public Nullable<decimal> itemname_homedelivary_total { get; set; }
    
        public virtual vel_restro_itemcategory vel_restro_itemcategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vel_restro_order> vel_restro_order { get; set; }
        public virtual vel_restro_restaurent vel_restro_restaurent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vel_restro_table_transfer> vel_restro_table_transfer { get; set; }
    }
}
