//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelfoodsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vel_restro_takeaway
    {
        public int takeaway_id { get; set; }
        public int kot_id { get; set; }
        public string takeaway_discount { get; set; }
        public string takeaway_plan { get; set; }
        public Nullable<decimal> takeaway_amount { get; set; }
        public Nullable<decimal> takeaway_parecel { get; set; }
        public Nullable<decimal> takeaway_total { get; set; }
        public int restaurent_id { get; set; }
        public string insert_by { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
    
        public virtual vel_restro_restaurent vel_restro_restaurent { get; set; }
    }
}
