//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelfoodsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vel_restro_paidouts
    {
        public int paidout_id { get; set; }
        public string paidout_name { get; set; }
        public string paidout_pariticular { get; set; }
        public string paidout_reportingname { get; set; }
        public string type_of_payment { get; set; }
        public string bank_name { get; set; }
        public string transaction_id { get; set; }
        public Nullable<decimal> Amoount { get; set; }
        public int restaurent_id { get; set; }
    
        public virtual vel_restro_restaurent vel_restro_restaurent { get; set; }
    }
}
