//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelfoodsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vel_restro_banks
    {
        public int bank_id { get; set; }
        public string bank_code { get; set; }
        public string bank_name { get; set; }
        public long bank_account_no { get; set; }
        public string bank_status { get; set; }
        public int empregistration_id { get; set; }
        public int restaurent_id { get; set; }
        public string bank_reporting_name { get; set; }
    
        public virtual vel_restro_empregistration vel_restro_empregistration { get; set; }
        public virtual vel_restro_restaurent vel_restro_restaurent { get; set; }
    }
}
