//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelfoodsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vel_restro_tabledefination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vel_restro_tabledefination()
        {
            this.vel_restro_order = new HashSet<vel_restro_order>();
        }
    
        public int table_defination_id { get; set; }
        public string table_name { get; set; }
        public int table_pax { get; set; }
        public string table_view { get; set; }
        public string table_description { get; set; }
        public string table_status { get; set; }
        public string table_capatain { get; set; }
        public string table_steward { get; set; }
        public int restaurent_id { get; set; }
        public string BACKGROUND_COLOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vel_restro_order> vel_restro_order { get; set; }
        public virtual vel_restro_restaurent vel_restro_restaurent { get; set; }
    }
}
