//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelfoodsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vel_restro_print
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vel_restro_print()
        {
            this.vel_restro_billpayment = new HashSet<vel_restro_billpayment>();
        }
    
        public int print_id { get; set; }
        public int table_defination_id { get; set; }
        public decimal total_amount { get; set; }
        public int offers_id { get; set; }
        public decimal discount_amount { get; set; }
        public string print_status { get; set; }
        public int restaurent_id { get; set; }
        public decimal total_after_discount { get; set; }
        public string insert_by { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vel_restro_billpayment> vel_restro_billpayment { get; set; }
        public virtual vel_restro_offers vel_restro_offers { get; set; }
        public virtual vel_restro_restaurent vel_restro_restaurent { get; set; }
        public virtual vel_restro_tabledefination vel_restro_tabledefination { get; set; }
    }
}
