//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelfoodsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vel_restro_itemcategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vel_restro_itemcategory()
        {
            this.vel_restro_itemname = new HashSet<vel_restro_itemname>();
        }
    
        public int itemcategory_id { get; set; }
        public string item_name { get; set; }
        public string item_description { get; set; }
        public System.DateTime item_active_from { get; set; }
        public string item_status { get; set; }
        public string item_reporting_name { get; set; }
        public int restaurent_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vel_restro_itemname> vel_restro_itemname { get; set; }
        public virtual vel_restro_restaurent vel_restro_restaurent { get; set; }
    }
}
