//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelfoodsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vel_restro_tablebooking
    {
        public int table_booking_id { get; set; }
        public string tablebookingf_name { get; set; }
        public int tablebooking_pax { get; set; }
        public long tablebooking_mobile_no { get; set; }
        public decimal tablebooking_advance { get; set; }
        public System.DateTime tablebooking_date { get; set; }
        public System.TimeSpan tablebooking_time { get; set; }
        public string tablebooking_splinstructions { get; set; }
        public int restaurent_id { get; set; }
    
        public virtual vel_restro_restaurent vel_restro_restaurent { get; set; }
    }
}
