//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelfoodsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vel_restro_empregistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vel_restro_empregistration()
        {
            this.vel_restro_banks = new HashSet<vel_restro_banks>();
            this.vel_restro_wallet = new HashSet<vel_restro_wallet>();
        }
    
        public int empregistration_id { get; set; }
        public string empregistration_name { get; set; }
        public long empregistration_mobile_no { get; set; }
        public string empregistration_email_id { get; set; }
        public string empregistration_id_proof { get; set; }
        public string empregistration_id_data { get; set; }
        public string empregistration_Address { get; set; }
        public int empdepartement_id { get; set; }
        public string empregistration_status { get; set; }
        public string empregistration_login_type { get; set; }
        public string Username { get; set; }
        public string password { get; set; }
        public int restaurent_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vel_restro_banks> vel_restro_banks { get; set; }
        public virtual vel_restro_empdepartment vel_restro_empdepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vel_restro_wallet> vel_restro_wallet { get; set; }
        public virtual vel_restro_restaurent vel_restro_restaurent { get; set; }
    }
}
